version: '3.8'
services:
  neo4j_temporal:
    image: neo4j:5.11
    restart: unless-stopped
    ports:
    - 7474:7474
    - 7687:7687
    environment:
    - NEO4J_AUTH=neo4j/password
    - NEO4J_PLUGINS=["apoc"]
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    networks:
    - cc_automator_network
    security_opt:
    - no-new-privileges:true
    volumes:
    - neo4j_temporal_data:/data
  chroma_historical:
    image: ghcr.io/chroma-core/chroma:latest
    restart: unless-stopped
    ports:
    - 8000:8000
    networks:
    - cc_automator_network
    security_opt:
    - no-new-privileges:true
    volumes:
    - chroma_historical_data:/chroma/chroma
networks:
  cc_automator_network:
    driver: bridge
    internal: false
volumes:
  neo4j_temporal_data: {}
  chroma_historical_data: {}
